- name: Testing...
  hosts: all
  connection: local
  become: yes
  become_user: root

  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest
    - name: Run echo command
      command: echo "MOI!"
      notify:
              - restart apache3

  handlers:
          - name: restart apache3
            service:
              name: apache2
              state: restarted
