- name: Testing...
  hosts: all
  connection: local
  become: yes
  become_user: root

  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest
    - name: Modify a line
      #      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>"
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:8081>" line="<VirtualHost *:80>"
      notify:
              - restart apache3

  handlers:
          - name: restart apache3
            service:
              name: apache2
              state: restarted
